apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deploy
  labels:
    {{- include "test-deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.vault.enabled }}
      annotations:
        vault.security.banzaicloud.io/vault-addr: {{ .Values.vault.url | quote }}
        vault.security.banzaicloud.io/vault-role: {{ .Values.vault.role | quote }}
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      {{- end }}
      labels:
        {{- include "test-deployment.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.vault.enabled }}
          - name: VAULT_ENABLED
            value: "true"
          - name: DEMO_SECRET
            value: vault:secret/data/demo#DEMO_SECRET
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
