apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "test-deployment.selectorLabels" . | nindent 4 }}
